# Generated by Django 5.2.8 on 2025-12-01 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('verificado', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Suspenso'), (3, 'Desativado')], default=1)),
                ('privacidade_padrao', models.SmallIntegerField(choices=[(1, 'Público'), (2, 'Privado')], default=1)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ElementoSonho',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_elemento', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('contagem_usos', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'elementos_sonhos',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id_hashtag', models.AutoField(primary_key=True, serialize=False)),
                ('texto_hashtag', models.CharField(max_length=50, unique=True)),
                ('contagem_uso', models.IntegerField(default=1)),
                ('primeira_utilizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_utilizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoUsuario',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notificacoes_novas_publicacoes', models.BooleanField(default=True)),
                ('notificacoes_comentarios', models.BooleanField(default=True)),
                ('notificacoes_seguidor_novo', models.BooleanField(default=True)),
                ('notificacoes_reacoes', models.BooleanField(default=True)),
                ('notificacoes_mensagens_diretas', models.BooleanField(default=True)),
                ('tema_interface', models.SmallIntegerField(choices=[(1, 'Claro'), (2, 'Escuro'), (3, 'Sistema')], default=1)),
                ('idioma', models.CharField(default='pt-BR', max_length=10)),
                ('mostrar_visualizacoes', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'configuracoes_usuario',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_conteudo', models.SmallIntegerField(choices=[(1, 'Publicação'), (2, 'Comentário'), (3, 'Usuário')])),
                ('id_conteudo', models.IntegerField()),
                ('motivo_denuncia', models.SmallIntegerField(choices=[(1, 'Conteúdo Inadequado'), (2, 'Assédio'), (3, 'Spam')])),
                ('descricao_denuncia', models.TextField(blank=True, null=True)),
                ('data_denuncia', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_denuncia', models.SmallIntegerField(choices=[(1, 'Pendente'), (2, 'Analisada'), (3, 'Resolvida')], default=1)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('acao_tomada', models.SmallIntegerField(blank=True, choices=[(1, 'Nenhuma'), (2, 'Removido'), (3, 'Usuário Suspenso')], null=True)),
                ('usuario_denunciante', models.ForeignKey(db_column='id_usuario_denunciante', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'denuncias',
            },
        ),
        migrations.CreateModel(
            name='EstatisticaSonho',
            fields=[
                ('id_estatistica', models.AutoField(primary_key=True, serialize=False)),
                ('total_sonhos', models.IntegerField(default=0)),
                ('pesadelos_registrados', models.IntegerField(default=0)),
                ('sonhos_lucidos_registrados', models.IntegerField(default=0)),
                ('elementos_recorrentes_top', models.JSONField(blank=True, null=True)),
                ('padrao_sono_medio', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimo_calculo', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estatisticas_sonhos',
            },
        ),
        migrations.CreateModel(
            name='ListaAmigosProximos',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nome_lista', models.CharField(default='Amigos Próximos', max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_dono', models.ForeignKey(db_column='id_usuario_dono', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lista_amigos_proximos',
            },
        ),
        migrations.CreateModel(
            name='MensagemDireta',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('deletada_remetente', models.BooleanField(default=False)),
                ('deletada_destinatario', models.BooleanField(default=False)),
                ('usuario_destinatario', models.ForeignKey(db_column='id_usuario_destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_remetente', models.ForeignKey(db_column='id_usuario_remetente', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens_diretas',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacao', models.SmallIntegerField(choices=[(1, 'Nova Publicação'), (2, 'Comentário'), (3, 'Curtida'), (4, 'Seguidor Novo')])),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('usuario_destino', models.ForeignKey(db_column='id_usuario_destino', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_origem', models.ForeignKey(blank=True, db_column='id_usuario_origem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_geradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id_publicacao', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo_texto', models.TextField()),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('data_sonho', models.DateField(blank=True, null=True)),
                ('tipo_sonho', models.CharField(blank=True, max_length=50, null=True)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('editado', models.BooleanField(default=False)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('visibilidade', models.SmallIntegerField(choices=[(1, 'Público'), (2, 'Lista de Amigos'), (3, 'Privado')], default=1)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('emocoes_sentidas', models.TextField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicacoes',
            },
        ),
        migrations.CreateModel(
            name='MidiaPublicacao',
            fields=[
                ('id_midia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_midia', models.SmallIntegerField(choices=[(1, 'Imagem'), (2, 'Vídeo'), (3, 'GIF'), (4, 'Áudio')])),
                ('url_midia', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('posicao_ordem', models.SmallIntegerField(default=0)),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamanho_bytes', models.IntegerField(blank=True, null=True)),
                ('largura', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
            ],
            options={
                'db_table': 'midia_publicacoes',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo_texto', models.TextField()),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('editado', models.BooleanField(default=False)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Removido'), (3, 'Denunciado')], default=1)),
                ('comentario_pai', models.ForeignKey(blank=True, db_column='id_comentario_pai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='core.comentario')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='MembroListaAmigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('lista', models.ForeignKey(db_column='id_lista', on_delete=django.db.models.deletion.CASCADE, to='core.listaamigosproximos')),
                ('usuario_membro', models.ForeignKey(db_column='id_usuario_membro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membros_lista_amigos',
                'unique_together': {('lista', 'usuario_membro')},
            },
        ),
        migrations.CreateModel(
            name='PublicacaoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_associacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('elemento', models.ForeignKey(db_column='id_elemento', on_delete=django.db.models.deletion.CASCADE, to='core.elementosonho')),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
            ],
            options={
                'db_table': 'publicacao_elementos',
                'unique_together': {('publicacao', 'elemento')},
            },
        ),
        migrations.CreateModel(
            name='PublicacaoHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_associacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hashtag', models.ForeignKey(db_column='id_hashtag', on_delete=django.db.models.deletion.CASCADE, to='core.hashtag')),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
            ],
            options={
                'db_table': 'publicacao_hashtags',
                'unique_together': {('publicacao', 'hashtag')},
            },
        ),
        migrations.CreateModel(
            name='ReacaoComentario',
            fields=[
                ('id_reacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reacao', models.SmallIntegerField(choices=[(1, 'Gostei'), (2, 'Amei'), (3, 'Confuso'), (4, 'Assustado'), (5, 'Relacionável')])),
                ('data_reacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.ForeignKey(db_column='id_comentario', on_delete=django.db.models.deletion.CASCADE, to='core.comentario')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reacoes_comentarios',
                'unique_together': {('comentario', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ReacaoPublicacao',
            fields=[
                ('id_reacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_reacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reacoes_publicacoes',
                'unique_together': {('publicacao', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id_seguidor', models.AutoField(primary_key=True, serialize=False)),
                ('data_seguimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Bloqueado')], default=1)),
                ('usuario_seguido', models.ForeignKey(db_column='id_usuario_seguido', on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('usuario_seguidor', models.ForeignKey(db_column='id_usuario_seguidor', on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seguidores',
                'unique_together': {('usuario_seguidor', 'usuario_seguido')},
            },
        ),
    ]
