# Generated by Django 5.2.8 on 2026-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pergunta_secreta',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Qual o nome do seu primeiro animal de estimação?'), (2, 'Qual o nome da sua cidade natal?'), (3, 'Qual era o nome da sua escola primária?'), (4, 'Qual o nome do seu melhor amigo de infância?'), (5, 'Qual o modelo do seu primeiro carro?')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='resposta_secreta',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
