# Generated by Django 5.2.8 on 2026-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_pergunta_secreta_usuario_resposta_secreta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='mostrar_feed_algoritmico',
            field=models.BooleanField(default=True),
        ),
    ]
