# Generated by Django 5.2.8 on 2026-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguidor',
            name='is_close_friend',
            field=models.BooleanField(default=False),
        ),
    ]
