# Generated by Django 5.2.8 on 2026-01-19 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seguidor_is_close_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salvo',
            fields=[
                ('id_salvo', models.AutoField(primary_key=True, serialize=False)),
                ('data_salvo', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salvos',
                'unique_together': {('usuario', 'publicacao')},
            },
        ),
    ]
