# Generated by Django 5.2.8 on 2026-01-19 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoSalva',
            fields=[
                ('id_salvo', models.AutoField(primary_key=True, serialize=False)),
                ('data_salvo', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacao', models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to='core.publicacao')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_salvas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicacoes_salvas',
                'unique_together': {('publicacao', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Salvo',
        ),
    ]
