# Generated by Django 5.2.8 on 2026-01-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publicacaosalva_delete_salvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaosalva',
            name='publicacao',
            field=models.ForeignKey(db_column='id_publicacao', on_delete=django.db.models.deletion.CASCADE, to='core.publicacao'),
        ),
        migrations.AlterField(
            model_name='publicacaosalva',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
