# Generated by Django 5.2.8 on 2026-01-22 17:58

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_publicacaosalva_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_notificacao',
            field=models.SmallIntegerField(choices=[(1, 'Nova Publicação'), (2, 'Comentário'), (3, 'Curtida'), (4, 'Seguidor Novo'), (5, 'Solicitação de Seguidor')]),
        ),
        migrations.AlterField(
            model_name='seguidor',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Bloqueado'), (3, 'Pendente')], default=1),
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id_comunidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='community_images/')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comunidades',
            },
        ),
    ]
