# Generated by Django 5.2.8 on 2026-01-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notificacao_tipo_notificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='comunidade',
            field=models.ForeignKey(blank=True, db_column='id_comunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='core.comunidade'),
        ),
    ]
