# Generated by Django 5.2.8 on 2026-01-27 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publicacao_comunidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='membros',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='regras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='MembroComunidade',
            fields=[
                ('id_membro', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='member', max_length=20)),
                ('is_moderator', models.BooleanField(default=False)),
                ('comunidade', models.ForeignKey(db_column='id_comunidade', on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membros_comunidade',
                'unique_together': {('comunidade', 'usuario')},
            },
        ),
    ]
