# Generated by Django 5.2.8 on 2026-01-27 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comunidade_membros_comunidade_regras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='comunidades', through='core.MembroComunidade', to=settings.AUTH_USER_MODEL),
        ),
    ]
