# Generated by Django 5.2.8 on 2026-01-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comunidade_membros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rascunho',
            fields=[
                ('id_rascunho', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('conteudo_texto', models.TextField(blank=True, default='')),
                ('tipo_post', models.CharField(choices=[('texto', 'Texto'), ('multimidia', 'Multimídia'), ('link', 'Link')], default='texto', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='drafts/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comunidade', models.ForeignKey(blank=True, db_column='id_comunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comunidade')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='rascunhos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rascunhos',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
