# Generated by Django 5.2.8 on 2026-01-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='conteudo_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
