# Generated by Django 5.2.8 on 2026-02-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
    ]
