# Generated by Django 5.2.8 on 2026-02-09 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comunidade_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanimentoComunidade',
            fields=[
                ('id_ban', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, default='')),
                ('data_ban', models.DateTimeField(default=django.utils.timezone.now)),
                ('comunidade', models.ForeignKey(db_column='id_comunidade', on_delete=django.db.models.deletion.CASCADE, related_name='banimentos', to='core.comunidade')),
                ('moderador', models.ForeignKey(db_column='id_moderador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_aplicados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='bans_comunidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banimentos_comunidade',
                'unique_together': {('comunidade', 'usuario')},
            },
        ),
    ]
