# Generated by Django 5.2.8 on 2026-02-10 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_banimentocomunidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id_bloqueio', models.AutoField(primary_key=True, serialize=False)),
                ('data_bloqueio', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_feitos', to=settings.AUTH_USER_MODEL)),
                ('usuario_bloqueado', models.ForeignKey(db_column='id_usuario_bloqueado', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloqueios',
                'unique_together': {('usuario', 'usuario_bloqueado')},
            },
        ),
        migrations.CreateModel(
            name='Silenciamento',
            fields=[
                ('id_silenciamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_silenciamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='silenciamentos_feitos', to=settings.AUTH_USER_MODEL)),
                ('usuario_silenciado', models.ForeignKey(db_column='id_usuario_silenciado', on_delete=django.db.models.deletion.CASCADE, related_name='silenciamentos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'silenciamentos',
                'unique_together': {('usuario', 'usuario_silenciado')},
            },
        ),
    ]
