# Generated by Django 5.2.8 on 2026-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bloqueio_silenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dream_videos/'),
        ),
    ]
